services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
